# Generated by Django 4.0.4 on 2022-05-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('u', 'unfinished'), ('f', 'finished')], default='u', help_text='Task status', max_length=1),
        ),
    ]
